INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Abia State', 'ABIA', 'ABIA', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Adamawa State', 'ADAMAWA', 'ADM', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Akwa Ibom State', 'AKWA_IBOM', 'AKW', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Anambra State', 'ANAMBRA', 'ANM', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Bauchi State', 'BAUCHI', 'BAU', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Bayelsa State', 'BAYELSA', 'BAY', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Benue State', 'BENUE', 'BEN', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Borno State', 'BORNO', 'BOR', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Cross River State', 'CROSS_RIVER', 'CRS', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Delta State', 'DELTA', 'DEL', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Ebonyi State', 'EBONYI', 'EBO', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Edo State', 'EDO', 'EDO', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Ekiti State', 'EKITI', 'EKI', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Enugu State', 'ENUGU', 'ENU', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('FCT', 'FCT', 'FCT', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Gombe State', 'GOMBE', 'GMB', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Imo State', 'IMO', 'IMO', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Jigawa State', 'JIGAWA', 'JIG', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Kaduna State', 'KADUNA', 'KAD', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Kano State', 'KANO', 'KAN', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Katsina State', 'KATSINA', 'KAT', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Kebbi State', 'KEBBI', 'KEB',  null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Kogi State', 'KOGI', 'KOG', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Kwara State', 'KWARA', 'KWA', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Lagos State', 'LAGOS', 'LAG', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Nasarawa State', 'NASARAWA', 'NAS', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Niger State', 'NIGER', 'NIG', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Ogun State', 'OGUN', 'OGU', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Ondo State', 'ONDO', 'OND', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Osun State', 'OSUN', 'OSU', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Oyo State', 'OYO', 'OYO',null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Plateau State', 'PLATEAU', 'PLA', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Rivers State', 'RIVERS', 'RIV', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Sokoto State', 'SOKOTO', 'SOK', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Taraba State', 'TARABA', 'TAR', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Yobe State', 'YOBE', 'YOB', null, null);
INSERT INTO states (name, `key`, `alias`, created_at, updated_at) VALUES ('Zamfara State', 'ZAMFARA', 'ZAM', null, null);
